use_frameworks!

target 'ACDExtension_Example' do
  pod 'ACDExtension', :path => '../'
#  pod 'ACDExtension', '0.0.1'

  target 'ACDExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
